# Site settings
name: Christian Yap
title: Christian Yap | Computer Engineer
description: Computer and Environmental engineer focused on tackling the world's environmental issues
url: https://christianyap.github.io/ChristianYap/
baseurl: ""
email: yapc@mail.gvsu.edu
cover:https://christianyap.github.io/ChristianYap/img/og.png
logo:https://christianyap.github.io/ChristianYap/img/emojis/technologist.png
resume:https://christianyap.github.io/ChristianYap/resume.pdf
social:
  - title: email
    url: mailto:yapc@mail.gvsu.edu
  - title: twitter
    url: https://twitter.com/thephatyap
  - title: instagram
    url: https://instagram.com/thephatyap
  - title: github
    url: https://christianyap.github.io/
  - title: linkedin
    url: https://www.linkedin.com/in/christian-yap-3b0a57ba/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
